
# origin of type 2
filter_2_o_south = ['Bà Rịa - Vũng TàuThành phố Vũng Tàu', 'Bà Rịa - Vũng TàuHuyện Long Điền', 'Bà Rịa - Vũng TàuThị Xã Phú Mỹ',
                     'Bà Rịa - Vũng TàuHuyện Xuyên Mộc', 'Bà Rịa - Vũng TàuHuyện Châu Đức','Bà Rịa - Vũng Tàu','Bà Rịa - Vũng TàuThành phố Bà Rịa',
                     'Bà Rịa - Vũng TàuHuyện Đất Đỏ', 'Bình ThuậnThành phố Phan Thiết','Bình ThuậnHuyện Tuy Phong', 'Bình ThuậnHuyện Tánh Linh',
                     'Bình ThuậnThị xã La Gi', 'Bình ThuậnHuyện Hàm Thuận Nam','Bình ThuậnHuyện Hàm Thuận Bắc', 'Bình ThuậnHuyện Đức Linh',
                     'Bình ThuậnHuyện Phú Quý', 'Bình Thuận','Bình ThuậnHuyện Bắc Bình', 'Bình ThuậnHuyện Hàm Tân','Cà MauThành phố Cà Mau', 'Cà MauHuyện Thới Bình',
                     'Cà MauHuyện Cái Nước', 'Cà MauHuyện Đầm Dơi','Cà MauHuyện Trần Văn Thời', 'Cà MauHuyện Năm Căn','Cà MauHuyện Ngọc Hiển', 'Cà MauHuyện U Minh', 'Cà Mau',
                     'Cà MauHuyện Phú Tân', 'Lâm Đồng', 'Lâm ĐồngThành phố Bảo Lộc','Lâm ĐồngHuyện Đức Trọng', 'Lâm ĐồngHuyện Lâm Hà',
                     'Lâm ĐồngHuyện Đạ Tẻh', 'Lâm ĐồngHuyện Di Linh','Lâm ĐồngHuyện Đam Rông', 'Lâm ĐồngHuyện Đơn Dương',
                     'Lâm ĐồngHuyện Bảo Lâm', 'Lâm ĐồngThành phố Đà Lạt','Lâm ĐồngHuyện Đạ Huoai', 'Lâm ĐồngHuyện Lạc Dương',
                     'Lâm ĐồngHuyện Cát Tiên']

filter_2_o_central = ['Đà Nẵng', 'Đà NẵngQuận Thanh Khê', 'Đà NẵngHuyện Hòa Vang','Đà NẵngQuận Liên Chiểu', 'Đà NẵngQuận Ngũ Hành Sơn',
                     'Đà NẵngQuận Hải Châu', 'Đà NẵngQuận Cẩm Lệ','Đà NẵngQuận Sơn Trà', 'Quảng BìnhThành Phố Đồng Hới',
                     'Quảng BìnhHuyện Quảng Trạch', 'Quảng BìnhHuyện Lệ Thủy','Quảng BìnhHuyện Bố Trạch', 'Quảng BìnhHuyện Minh Hóa',
                     'Quảng BìnhHuyện Quảng Ninh', 'Quảng BìnhHuyện Tuyên Hóa','Quảng BìnhThị xã Ba Đồn', 'Quảng Bình','Quảng NamThành phố Tam Kỳ', 'Quảng NamThành phố Hội An',
                     'Quảng NamHuyện Núi Thành', 'Quảng NamHuyện Quế Sơn','Quảng NamHuyện Bắc Trà My', 'Quảng NamHuyện Hiệp Đức',
                     'Quảng NamHuyện Nam Giang', 'Quảng NamHuyện Đại Lộc','Quảng NamHuyện Tiên Phước', 'Quảng NamHuyện Nông Sơn',
                     'Quảng NamHuyện Phước Sơn', 'Quảng NamHuyện Tây Giang','Quảng NamHuyện Đông Giang', 'Quảng NamHuyện Nam Trà My',
                     'Quảng Nam', 'Quảng NamHuyện Duy Xuyên','Quảng NamThị xã Điện Bàn', 'Quảng NamHuyện Thăng Bình',
                     'Quảng NamHuyện Phú Ninh', 'Quảng TrịThị xã Quảng Trị','Quảng TrịHuyện Hướng Hóa', 'Quảng TrịHuyện Hải Lăng',
                     'Quảng TrịHuyện Vĩnh Linh', 'Quảng TrịThành phố Đông Hà','Quảng TrịHuyện Gio Linh', 'Quảng TrịHuyện Triệu Phong',
                     'Quảng Trị', 'Quảng TrịHuyện Đa Krông', 'Quảng TrịHuyện Cam Lộ','Thừa Thiên HuếThành phố Huế', 'Thừa Thiên HuếHuyện Phú Lộc',
                     'Thừa Thiên HuếHuyện Phong Điền', 'Thừa Thiên HuếHuyện A Lưới','Thừa Thiên HuếThị xã Hương Trà',
                     'Thừa Thiên HuếThị xã Hương Thủy',
                     'Thừa Thiên HuếHuyện Quảng Điền', 'Thừa Thiên Huế',
                     'Thừa Thiên HuếHuyện Phú Vang', 'Thừa Thiên HuếHuyện Nam Đông']

filter_2_o_hcm = ['Hồ Chí MinhQuận Bình Tân', 'Hồ Chí Minh',
       'Hồ Chí MinhHuyện Củ Chi', 'Hồ Chí MinhQuận Bình Thạnh',
       'Hồ Chí MinhQuận 10', 'Hồ Chí MinhQuận 2',
       'Hồ Chí MinhQuận Gò Vấp', 'Hồ Chí MinhQuận 12',
       'Hồ Chí MinhQuận 6', 'Hồ Chí MinhQuận 9',
       'Hồ Chí MinhQuận Tân Phú', 'Hồ Chí MinhQuận Thủ Đức',
       'Hồ Chí MinhHuyện Hóc Môn', 'Hồ Chí MinhQuận Phú Nhuận',
       'Hồ Chí MinhQuận 4', 'Hồ Chí MinhHuyện Bình Chánh',
       'Hồ Chí MinhQuận Tân Bình', 'Hồ Chí MinhHuyện Cần Giờ',
       'Hồ Chí MinhHuyện Nhà Bè', 'Hồ Chí MinhQuận 3',
       'Hồ Chí MinhQuận 5', 'Hồ Chí MinhThành phố Thủ Đức',
       'Hồ Chí MinhQuận 11', 'Hồ Chí MinhQuận 1', 'Hồ Chí MinhQuận 7',
       'Hồ Chí MinhQuận 8']

filter_2_o_hn = ['Hà NộiQuận Long Biên', 'Hà Nội', 'Hà NộiHuyện Quốc Oai',
       'Hà NộiQuận Hà Đông', 'Hà NộiQuận Hoàng Mai',
       'Hà NộiQuận Nam Từ Liêm', 'Hà NộiQuận Đống Đa',
       'Hà NộiHuyện Đông Anh', 'Hà NộiThị xã Sơn Tây',
       'Hà NộiHuyện Thường Tín', 'Hà NộiHuyện Mỹ Đức',
       'Hà NộiHuyện Chương Mỹ', 'Hà NộiHuyện Sóc Sơn',
       'Hà NộiQuận Ba Đình', 'Hà NộiQuận Hai Bà Trưng',
       'Hà NộiHuyện Ứng Hòa', 'Hà NộiQuận Cầu Giấy',
       'Hà NộiHuyện Đan Phượng', 'Hà NộiHuyện Thanh Oai',
       'Hà NộiHuyện Thanh Trì', 'Hà NộiHuyện Thạch Thất',
       'Hà NộiHuyện Gia Lâm', 'Hà NộiQuận Hoàn Kiếm', 'Hà NộiQuận Tây Hồ',
       'Hà NộiHuyện Mê Linh', 'Hà NộiQuận Thanh Xuân',
       'Hà NộiHuyện Phú Xuyên', 'Hà NộiHuyện Ba Vì',
       'Hà NộiHuyện Hoài Đức', 'Hà NộiHuyện Phúc Thọ',
       'Hà NộiQuận Bắc Từ Liêm']

filter_2_o_north = ['Bắc KạnThành Phố Bắc Kạn', 'Bắc KạnHuyện Ngân Sơn',
       'Bắc KạnHuyện Na Rì', 'Bắc KạnHuyện Chợ Mới',
       'Bắc KạnHuyện Chợ Đồn', 'Bắc KạnHuyện Ba Bể',
       'Bắc KạnHuyện Pác Nặm', 'Bắc KạnHuyện Bạch Thông',
       'Cao BằngThành phố Cao Bằng', 'Cao BằngHuyện Trà Lĩnh',
       'Cao BằngHuyện Hà Quảng', 'Cao BằngHuyện Thông Nông',
       'Cao BằngHuyện Thạch An', 'Cao BằngHuyện Quảng Uyên',
       'Cao BằngHuyện Trùng Khánh', 'Cao BằngHuyện Hạ Lang',
       'Cao BằngHuyện Bảo Lạc', 'Cao BằngHuyện Bảo Lâm',
       'Cao BằngHuyện Phục Hoà', 'Cao BằngHuyện Nguyên Bình',
       'Cao BằngHuyện Hoà An', 'Cao BằngHuyện Quảng Hòa',
       'Hà GiangThành phố Hà Giang', 'Hà GiangHuyện Bắc Mê',
       'Hà GiangHuyện Bắc Quang', 'Hà GiangHuyện Quản Bạ',
       'Hà GiangHuyện Vị Xuyên', 'Hà GiangHuyện Yên Minh',
       'Hà GiangHuyện Mèo Vạc', 'Hà GiangHuyện Đồng Văn',
       'Hà GiangHuyện Hoàng Su Phì', 'Hà GiangHuyện Xín Mần',
       'Hà GiangHuyện Quang Bình', 'Lai ChâuThành phố Lai Châu',
       'Lai ChâuHuyện Than Uyên', 'Lai ChâuHuyện Tân Uyên',
       'Lai ChâuHuyện Phong Thổ', 'Lai ChâuHuyện Sìn Hồ',
       'Lai ChâuHuyện Nậm Nhùn', 'Lai ChâuHuyện Mường Tè', 'Lai Châu',
       'Lai ChâuHuyện Tam Đường', 'Lạng SơnThành phố Lạng Sơn',
       'Lạng SơnHuyện Bình Gia', 'Lạng SơnHuyện Văn Lãng',
       'Lạng SơnHuyện Cao Lộc', 'Lạng SơnHuyện Lộc Bình',
       'Lạng SơnHuyện Bắc Sơn', 'Lạng SơnHuyện Chi Lăng',
       'Lạng SơnHuyện Đình Lập', 'Lạng SơnHuyện Hữu Lũng',
       'Lạng SơnHuyện Tràng Định', 'Lạng SơnHuyện Văn Quan', 'Lạng Sơn',
       'Lào CaiThành phố Lào Cai', 'Lào CaiHuyện Bảo Thắng',
       'Lào CaiHuyện Sa Pa', 'Lào CaiThị xã Sa Pa',
       'Lào CaiHuyện Bảo Yên', 'Lào CaiHuyện Văn Bàn',
       'Lào CaiHuyện Bắc Hà', 'Lào CaiHuyện Bát Xát',
       'Lào CaiHuyện Mường Khương', 'Lào CaiHuyện Si Ma Cai', 'Nghệ An',
       'Nghệ AnThị xã Hoàng Mai', 'Nghệ AnHuyện Nam Đàn',
       'Nghệ AnHuyện Tân Kỳ', 'Nghệ AnHuyện Quỳ Châu',
       'Nghệ AnThị xã Thái Hoà', 'Nghệ AnHuyện Thanh Chương',
       'Nghệ AnHuyện Yên Thành', 'Nghệ AnHuyện Quỳ Hợp',
       'Nghệ AnHuyện Anh Sơn', 'Nghệ AnHuyện Quế Phong',
       'Nghệ AnHuyện Con Cuông', 'Nghệ AnHuyện Tương Dương',
       'Nghệ AnThành phố Vinh', 'Nghệ AnHuyện Kỳ Sơn',
       'Nghệ AnThị xã Cửa Lò', 'Nghệ AnHuyện Nghi Lộc',
       'Nghệ AnHuyện Diễn Châu', 'Nghệ AnHuyện Đô Lương',
       'Nghệ AnHuyện Hưng Nguyên', 'Nghệ AnHuyện Quỳnh Lưu',
       'Nghệ AnHuyện Nghĩa Đàn', 'Quảng Ninh',
       'Thanh HóaThành phố Thanh Hóa', 'Thanh HóaHuyện Thọ Xuân',
       'Thanh HóaThị xã Bỉm Sơn', 'Thanh HóaHuyện Tĩnh Gia',
       'Thanh HóaHuyện Hoằng Hóa', 'Thanh HóaHuyện Yên Định',
       'Thanh HóaHuyện Như Thanh', 'Thanh HóaHuyện Thạch Thành',
       'Thanh HóaHuyện Thường Xuân', 'Thanh HóaHuyện Quan Hóa',
       'Thanh HóaHuyện Quan Sơn', 'Thanh HóaHuyện Bá Thước',
       'Thanh HóaHuyện Ngọc Lặc', 'Thanh HóaHuyện Mường Lát',
       'Thanh HóaHuyện Lang Chánh', 'Thanh HóaHuyện Quảng Xương',
       'Thanh HóaHuyện Thiệu Hóa', 'Thanh Hóa', 'Thanh HóaHuyện Nga Sơn',
       'Thanh HóaHuyện Nông Cống', 'Thanh HóaHuyện Triệu Sơn',
       'Thanh HóaHuyện Cẩm Thủy', 'Thanh HóaHuyện Hậu Lộc',
       'Thanh HóaHuyện Vĩnh Lộc', 'Thanh HóaThành phố Sầm Sơn',
       'Thanh HóaHuyện Đông Sơn', 'Thanh HóaHuyện Hà Trung',
       'Thanh HóaThị xã Nghi Sơn', 'Thanh HóaHuyện Như Xuân',
       'Tuyên QuangThành phố Tuyên Quang', 'Tuyên QuangHuyện Sơn Dương',
       'Tuyên QuangHuyện Chiêm Hóa', 'Tuyên QuangHuyện Yên Sơn',
       'Tuyên QuangHuyện Nà Hang', 'Tuyên QuangHuyện Hàm Yên',
       'Tuyên QuangHuyện Lâm Bình', 'Yên BáiThành phố Yên Bái',
       'Yên BáiThị xã Nghĩa Lộ', 'Yên BáiHuyện Văn Yên',
       'Yên BáiHuyện Văn Chấn', 'Yên BáiHuyện Mù Căng Chải',
       'Yên BáiHuyện Lục Yên', 'Yên BáiHuyện Yên Bình',
       'Yên BáiHuyện Trạm Tấu', 'Yên BáiHuyện Trấn Yên']

filter_2_o_northHY = ['Hưng YênThành phố Hưng Yên', 'Hưng YênHuyện Yên Mỹ',
       'Hưng YênHuyện Mỹ Hào', 'Hưng YênThị xã Mỹ Hào', 'Hưng Yên',
       'Hưng YênHuyện Văn Lâm', 'Hưng YênHuyện Khoái Châu',
       'Hưng YênHuyện Phù Cừ', 'Hưng YênHuyện Ân Thi',
       'Hưng YênHuyện Văn Giang', 'Hưng YênHuyện Kim Động',
       'Hưng YênHuyện Tiên Lữ', 'Quảng NinhThành phố Hạ Long',
       'Quảng NinhThành phố Cẩm Phả', 'Quảng NinhThành phố Uông Bí',
       'Quảng NinhThành phố Móng Cái', 'Quảng NinhHuyện Tiên Yên',
       'Quảng NinhThị xã Đông Triều', 'Quảng NinhHuyện Hải Hà',
       'Quảng NinhHuyện Cô Tô', 'Quảng NinhHuyện Vân Đồn', 'Quảng Ninh',
       'Quảng NinhHuyện Ba Chẽ', 'Quảng NinhThị xã Quảng Yên',
       'Quảng NinhHuyện Bình Liêu', 'Quảng NinhHuyện Đầm Hà',
       'Quảng NinhHuyện Hoành Bồ']

filter_2_o_southNTR = ['Khánh Hòa', 'Khánh HòaThành phố Cam Ranh',
       'Khánh HòaThành phố Nha Trang', 'Khánh HòaHuyện Vạn Ninh',
       'Khánh HòaThị xã Ninh Hòa', 'Khánh HòaHuyện Khánh Vĩnh',
       'Khánh HòaHuyện Cam Lâm', 'Khánh HòaHuyện Khánh Sơn',
       'Khánh HòaHuyện Diên Khánh']

# destination of type 2
filter_2_d_central = ['Đà NẵngQuận Thanh Khê', 'Đà Nẵng']

filter_2_d_central1 = ['Đà Nẵng', 'Đà NẵngHuyện Hòa Vang', 'Đà NẵngQuận Liên Chiểu',
       'Đà NẵngQuận Ngũ Hành Sơn', 'Đà NẵngQuận Hải Châu',
       'Đà NẵngQuận Cẩm Lệ', 'Đà NẵngQuận Sơn Trà',
       'Quảng BìnhThành Phố Đồng Hới', 'Quảng BìnhHuyện Lệ Thủy',
       'Quảng BìnhHuyện Bố Trạch', 'Quảng BìnhHuyện Quảng Ninh',
       'Quảng Bình', 'Quảng NamThành phố Tam Kỳ',
       'Quảng NamThành phố Hội An', 'Quảng NamHuyện Núi Thành',
       'Quảng NamHuyện Quế Sơn', 'Quảng NamHuyện Bắc Trà My',
       'Quảng NamHuyện Hiệp Đức', 'Quảng NamHuyện Nam Giang',
       'Quảng NamHuyện Đại Lộc', 'Quảng NamHuyện Tiên Phước',
       'Quảng NamHuyện Phước Sơn', 'Quảng NamHuyện Tây Giang',
       'Quảng NamHuyện Đông Giang', 'Quảng NamHuyện Nam Trà My',
       'Quảng Nam', 'Quảng NamHuyện Duy Xuyên',
       'Quảng NamThị xã Điện Bàn', 'Quảng NamHuyện Thăng Bình',
       'Quảng NamHuyện Phú Ninh', 'Quảng TrịThị xã Quảng Trị',
       'Quảng TrịHuyện Hướng Hóa', 'Quảng TrịHuyện Hải Lăng',
       'Quảng TrịThành phố Đông Hà', 'Quảng TrịHuyện Gio Linh',
       'Quảng Trị', 'Quảng TrịHuyện Đa Krông', 'Quảng TrịHuyện Cam Lộ',
       'Thừa Thiên HuếThành phố Huế', 'Thừa Thiên HuếHuyện Phú Lộc',
       'Thừa Thiên HuếHuyện Phong Điền', 'Thừa Thiên HuếThị xã Hương Trà',
       'Thừa Thiên HuếThị xã Hương Thủy', 'Thừa Thiên Huế',
       'Thừa Thiên HuếHuyện Phú Vang', 'Thừa Thiên HuếHuyện Nam Đông']

filter_2_d_central2 = ['Quảng BìnhHuyện Quảng Trạch', 'Quảng BìnhHuyện Minh Hóa',
       'Quảng BìnhHuyện Tuyên Hóa', 'Quảng BìnhThị xã Ba Đồn',
       'Quảng NamHuyện Nông Sơn', 'Quảng TrịHuyện Vĩnh Linh',
       'Quảng TrịHuyện Triệu Phong', 'Thừa Thiên HuếHuyện A Lưới',
       'Thừa Thiên HuếHuyện Quảng Điền']

filter_2_d_hcm = ['Hồ Chí MinhQuận Bình Tân', 'Hồ Chí Minh',
       'Hồ Chí MinhQuận Bình Thạnh', 'Hồ Chí MinhQuận 10',
       'Hồ Chí MinhQuận 2', 'Hồ Chí MinhQuận Gò Vấp', 'Hồ Chí MinhQuận 6',
       'Hồ Chí MinhQuận Tân Phú', 'Hồ Chí MinhQuận Thủ Đức',
       'Hồ Chí MinhQuận Phú Nhuận', 'Hồ Chí MinhQuận 4',
       'Hồ Chí MinhQuận Tân Bình', 'Hồ Chí MinhQuận 3',
       'Hồ Chí MinhQuận 5', 'Hồ Chí MinhQuận 11', 'Hồ Chí MinhQuận 1',
       'Hồ Chí MinhQuận 7', 'Hồ Chí MinhQuận 8']

filter_2_d_hcm2 = ['Hồ Chí MinhHuyện Củ Chi', 'Hồ Chí Minh', 'Hồ Chí MinhQuận 12',
       'Hồ Chí MinhQuận 9', 'Hồ Chí MinhHuyện Hóc Môn',
       'Hồ Chí MinhHuyện Bình Chánh', 'Hồ Chí MinhHuyện Cần Giờ',
       'Hồ Chí MinhHuyện Nhà Bè', 'Hồ Chí MinhThành phố Thủ Đức']

filter_2_d_hn = ['Hà NộiQuận Long Biên', 'Hà Nội', 'Hà NộiQuận Hoàng Mai',
       'Hà NộiQuận Đống Đa', 'Hà NộiQuận Ba Đình',
       'Hà NộiQuận Hai Bà Trưng', 'Hà NộiQuận Cầu Giấy',
       'Hà NộiQuận Hoàn Kiếm', 'Hà NộiQuận Tây Hồ',
       'Hà NộiQuận Thanh Xuân']

filter_2_d_hn2 = ['Hà Nội', 'Hà NộiHuyện Quốc Oai', 'Hà NộiQuận Hà Đông',
       'Hà NộiQuận Nam Từ Liêm', 'Hà NộiHuyện Đông Anh',
       'Hà NộiThị xã Sơn Tây', 'Hà NộiHuyện Thường Tín',
       'Hà NộiHuyện Mỹ Đức', 'Hà NộiHuyện Chương Mỹ',
       'Hà NộiHuyện Sóc Sơn', 'Hà NộiHuyện Ứng Hòa',
       'Hà NộiHuyện Đan Phượng', 'Hà NộiHuyện Thanh Oai',
       'Hà NộiHuyện Thanh Trì', 'Hà NộiHuyện Thạch Thất',
       'Hà NộiHuyện Gia Lâm', 'Hà NộiHuyện Mê Linh',
       'Hà NộiHuyện Phú Xuyên', 'Hà NộiHuyện Ba Vì',
       'Hà NộiHuyện Hoài Đức', 'Hà NộiHuyện Phúc Thọ',
       'Hà NộiQuận Bắc Từ Liêm']

filter_2_d_north = ['Nghệ AnThành phố Vinh']

filter_2_d_north1 = ['Bắc KạnThành Phố Bắc Kạn', 'Bắc KạnHuyện Na Rì',
       'Bắc KạnHuyện Chợ Mới', 'Bắc KạnHuyện Bạch Thông',
       'Cao BằngThành phố Cao Bằng', 'Hà GiangThành phố Hà Giang',
       'Hưng Yên', 'Lạng SơnThành phố Lạng Sơn', 'Lạng SơnHuyện Chi Lăng',
       'Lạng SơnHuyện Hữu Lũng', 'Lạng Sơn', 'Lào CaiThành phố Lào Cai',
       'Thanh HóaThành phố Thanh Hóa', 'Thanh HóaHuyện Thọ Xuân',
       'Thanh HóaThị xã Bỉm Sơn', 'Thanh HóaHuyện Tĩnh Gia',
       'Thanh HóaHuyện Hoằng Hóa', 'Thanh HóaHuyện Quảng Xương',
       'Thanh HóaHuyện Thiệu Hóa', 'Thanh Hóa', 'Thanh HóaHuyện Nga Sơn',
       'Thanh HóaHuyện Nông Cống', 'Thanh HóaHuyện Triệu Sơn',
       'Thanh HóaHuyện Hậu Lộc', 'Thanh HóaThành phố Sầm Sơn',
       'Thanh HóaHuyện Đông Sơn', 'Thanh HóaHuyện Hà Trung',
       'Thanh HóaThị xã Nghi Sơn', 'Thanh HóaHuyện Như Xuân',
       'Tuyên QuangThành phố Tuyên Quang', 'Tuyên QuangHuyện Sơn Dương',
       'Tuyên QuangHuyện Yên Sơn', 'Tuyên QuangHuyện Hàm Yên',
       'Yên BáiThành phố Yên Bái', 'Yên BáiHuyện Yên Bình',
       'Yên BáiHuyện Trấn Yên']

filter_2_d_north2 = ['Bắc KạnHuyện Ngân Sơn', 'Bắc KạnHuyện Chợ Đồn',
       'Bắc KạnHuyện Ba Bể', 'Bắc KạnHuyện Pác Nặm',
       'Cao BằngHuyện Trà Lĩnh', 'Cao BằngHuyện Hà Quảng',
       'Cao BằngHuyện Thông Nông', 'Cao BằngHuyện Thạch An',
       'Cao BằngHuyện Quảng Uyên', 'Cao BằngHuyện Trùng Khánh',
       'Cao BằngHuyện Hạ Lang', 'Cao BằngHuyện Bảo Lạc',
       'Cao BằngHuyện Bảo Lâm', 'Cao BằngHuyện Phục Hoà',
       'Cao BằngHuyện Nguyên Bình', 'Cao BằngHuyện Hoà An',
       'Cao BằngHuyện Quảng Hòa', 'Hà GiangHuyện Bắc Mê',
       'Hà GiangHuyện Bắc Quang', 'Hà GiangHuyện Quản Bạ',
       'Hà GiangHuyện Vị Xuyên', 'Hà GiangHuyện Yên Minh',
       'Hà GiangHuyện Mèo Vạc', 'Hà GiangHuyện Đồng Văn',
       'Hà GiangHuyện Hoàng Su Phì', 'Hà GiangHuyện Xín Mần',
       'Hà GiangHuyện Quang Bình', 'Lai ChâuThành phố Lai Châu',
       'Lai ChâuHuyện Than Uyên', 'Lai ChâuHuyện Tân Uyên',
       'Lai ChâuHuyện Phong Thổ', 'Lai ChâuHuyện Sìn Hồ', 'Lai Châu',
       'Lai ChâuHuyện Tam Đường', 'Lạng SơnHuyện Bình Gia',
       'Lạng SơnHuyện Văn Lãng', 'Lạng SơnHuyện Cao Lộc',
       'Lạng SơnHuyện Lộc Bình', 'Lạng SơnHuyện Bắc Sơn',
       'Lạng SơnHuyện Đình Lập', 'Lạng SơnHuyện Tràng Định',
       'Lạng SơnHuyện Văn Quan', 'Lào CaiHuyện Bảo Thắng',
       'Lào CaiHuyện Sa Pa', 'Lào CaiThị xã Sa Pa',
       'Lào CaiHuyện Bảo Yên', 'Lào CaiHuyện Văn Bàn',
       'Lào CaiHuyện Bắc Hà', 'Lào CaiHuyện Bát Xát',
       'Lào CaiHuyện Mường Khương', 'Lào CaiHuyện Si Ma Cai',
       'Thanh HóaHuyện Yên Định', 'Thanh HóaHuyện Như Thanh',
       'Thanh HóaHuyện Thạch Thành', 'Thanh HóaHuyện Thường Xuân',
       'Thanh HóaHuyện Quan Hóa', 'Thanh HóaHuyện Quan Sơn',
       'Thanh HóaHuyện Bá Thước', 'Thanh HóaHuyện Ngọc Lặc',
       'Thanh HóaHuyện Mường Lát', 'Thanh HóaHuyện Lang Chánh',
       'Thanh HóaHuyện Cẩm Thủy', 'Thanh HóaHuyện Vĩnh Lộc',
       'Tuyên QuangHuyện Chiêm Hóa', 'Tuyên QuangHuyện Nà Hang',
       'Tuyên QuangHuyện Lâm Bình', 'Yên BáiThị xã Nghĩa Lộ',
       'Yên BáiHuyện Văn Yên', 'Yên BáiHuyện Văn Chấn',
       'Yên BáiHuyện Mù Căng Chải', 'Yên BáiHuyện Lục Yên',
       'Yên BáiHuyện Trạm Tấu']

filter_2_d_north3 = ['Lai ChâuHuyện Nậm Nhùn', 'Lai ChâuHuyện Mường Tè']

filter_2_d_north4 = ['Quảng NinhHuyện Cô Tô', 'Quảng NinhHuyện Vân Đồn']

filter_2_d_northHY = ['Hưng YênThành phố Hưng Yên', 'Hưng YênHuyện Yên Mỹ',
       'Hưng YênHuyện Mỹ Hào', 'Hưng YênThị xã Mỹ Hào',
       'Hưng YênHuyện Văn Lâm', 'Hưng YênHuyện Khoái Châu',
       'Hưng YênHuyện Phù Cừ', 'Hưng YênHuyện Ân Thi',
       'Hưng YênHuyện Văn Giang', 'Hưng YênHuyện Kim Động',
       'Hưng YênHuyện Tiên Lữ', 'Quảng NinhThành phố Hạ Long',
       'Quảng NinhThành phố Cẩm Phả', 'Quảng NinhThành phố Uông Bí',
       'Quảng NinhThành phố Móng Cái', 'Quảng NinhHuyện Tiên Yên',
       'Quảng NinhThị xã Đông Triều', 'Quảng NinhHuyện Hải Hà',
       'Quảng Ninh', 'Quảng NinhHuyện Ba Chẽ',
       'Quảng NinhThị xã Quảng Yên', 'Quảng NinhHuyện Bình Liêu',
       'Quảng NinhHuyện Đầm Hà', 'Quảng NinhHuyện Hoành Bồ']

filter_2_d_northVI = ['Nghệ An', 'Nghệ AnThị xã Hoàng Mai', 'Nghệ AnHuyện Nam Đàn',
       'Nghệ AnHuyện Tân Kỳ', 'Nghệ AnHuyện Quỳ Châu',
       'Nghệ AnThị xã Thái Hoà', 'Nghệ AnHuyện Thanh Chương',
       'Nghệ AnHuyện Yên Thành', 'Nghệ AnHuyện Quỳ Hợp',
       'Nghệ AnHuyện Anh Sơn', 'Nghệ AnHuyện Quế Phong',
       'Nghệ AnHuyện Con Cuông', 'Nghệ AnHuyện Tương Dương',
       'Nghệ AnHuyện Kỳ Sơn', 'Nghệ AnThị xã Cửa Lò',
       'Nghệ AnHuyện Nghi Lộc', 'Nghệ AnHuyện Diễn Châu',
       'Nghệ AnHuyện Đô Lương', 'Nghệ AnHuyện Hưng Nguyên',
       'Nghệ AnHuyện Quỳnh Lưu', 'Nghệ AnHuyện Nghĩa Đàn']

filter_2_d_south1 = ['Bà Rịa - Vũng TàuThành phố Vũng Tàu',
       'Bà Rịa - Vũng TàuHuyện Long Điền',
       'Bà Rịa - Vũng TàuThị Xã Phú Mỹ',
       'Bà Rịa - Vũng TàuHuyện Xuyên Mộc',
       'Bà Rịa - Vũng TàuHuyện Châu Đức',
       'Bà Rịa - Vũng TàuThành phố Bà Rịa', 'Bà Rịa - Vũng Tàu',
       'Bà Rịa - Vũng TàuHuyện Đất Đỏ', 'Bình ThuậnThành phố Phan Thiết',
       'Bình ThuậnHuyện Tuy Phong', 'Bình ThuậnHuyện Tánh Linh',
       'Bình ThuậnThị xã La Gi', 'Bình ThuậnHuyện Hàm Thuận Nam',
       'Bình ThuậnHuyện Hàm Thuận Bắc', 'Bình ThuậnHuyện Đức Linh',
       'Bình Thuận', 'Bình ThuậnHuyện Bắc Bình',
       'Bình ThuậnHuyện Hàm Tân', 'Cà MauThành phố Cà Mau',
       'Cà MauHuyện Thới Bình', 'Cà MauHuyện Cái Nước',
       'Cà MauHuyện Đầm Dơi', 'Cà MauHuyện Trần Văn Thời',
       'Cà MauHuyện U Minh', 'Cà Mau', 'Lâm Đồng',
       'Lâm ĐồngThành phố Bảo Lộc', 'Lâm ĐồngHuyện Đức Trọng',
       'Lâm ĐồngHuyện Đạ Tẻh', 'Lâm ĐồngHuyện Di Linh',
       'Lâm ĐồngHuyện Đam Rông', 'Lâm ĐồngHuyện Bảo Lâm',
       'Lâm ĐồngThành phố Đà Lạt', 'Lâm ĐồngHuyện Lạc Dương',
       'Lâm ĐồngHuyện Cát Tiên']

filter_2_d_south2 = ['Cà MauHuyện Năm Căn', 'Cà MauHuyện Ngọc Hiển',
       'Cà MauHuyện Phú Tân', 'Lâm ĐồngHuyện Lâm Hà',
       'Lâm ĐồngHuyện Đơn Dương', 'Lâm ĐồngHuyện Đạ Huoai']

filter_2_d_south4 = ['Bà Rịa - Vũng Tàu', 'Bình ThuậnHuyện Phú Quý', 'Khánh Hòa']

filter_2_d_southNTR = ['Khánh Hòa', 'Khánh HòaThành phố Cam Ranh',
       'Khánh HòaThành phố Nha Trang', 'Khánh HòaHuyện Vạn Ninh',
       'Khánh HòaThị xã Ninh Hòa', 'Khánh HòaHuyện Khánh Vĩnh',
       'Khánh HòaHuyện Cam Lâm', 'Khánh HòaHuyện Khánh Sơn',
       'Khánh HòaHuyện Diên Khánh']

# origin of type 3 
filter_3_o_central = ['Quảng NgãiThành phố Quảng Ngãi', 'Quảng NgãiHuyện Mộ Đức',
       'Quảng NgãiHuyện Bình Sơn', 'Quảng NgãiHuyện Ba Tơ',
       'Quảng NgãiHuyện Sơn Hà', 'Quảng NgãiHuyện Trà Bồng',
       'Quảng NgãiHuyện Lý Sơn', 'Quảng NgãiHuyện Nghĩa Hành',
       'Quảng NgãiHuyện Sơn Tịnh', 'Quảng NgãiThị xã Đức Phổ',
       'Quảng NgãiHuyện Tư Nghĩa', 'Quảng NgãiHuyện Sơn Tây',
       'Quảng NgãiHuyện Minh Long', 'Quảng NgãiHuyện Đức Phổ',
       'Quảng NgãiHuyện Tây Trà']

filter_3_o_north = ['Điện BiênHuyện Điện Biên', 'Điện BiênHuyện Tuần Giáo',
       'Điện BiênHuyện Mường Chà', 'Điện BiênHuyện Mường Nhé',
       'Điện BiênHuyện Tủa Chùa', 'Điện BiênHuyện Điện Biên Đông',
       'Điện Biên', 'Điện BiênThành phố Điện Biên Phủ',
       'Điện BiênThị Xã Mường Lay', 'Điện BiênHuyện Nậm Pồ',
       'Điện BiênHuyện Mường Ảng']

filter_3_o_south = ['Kiên GiangThành phố Rạch Giá', 'Kiên GiangHuyện Giồng Riềng',
       'Kiên GiangHuyện U Minh Thượng', 'Kiên GiangHuyện Hòn Đất',
       'Kiên GiangThành phố Hà Tiên', 'Kiên GiangThị xã Hà Tiên',
       'Kiên GiangHuyện Kiên Lương', 'Kiên Giang',
       'Kiên GiangHuyện Kiên Hải', 'Kiên GiangThành phố Phú Quốc',
       'Kiên GiangHuyện Phú Quốc', 'Kiên GiangHuyện An Biên',
       'Kiên GiangHuyện Tân Hiệp', 'Kiên GiangHuyện An Minh',
       'Kiên GiangHuyện Gò Quao', 'Kiên GiangHuyện Châu Thành',
       'Kiên GiangHuyện Giang Thành', 'Kiên GiangHuyện Vĩnh Thuận']

# destination of type 3
filter_3_d_central1 = ['Quảng NgãiThành phố Quảng Ngãi', 'Quảng NgãiHuyện Mộ Đức',
       'Quảng NgãiHuyện Bình Sơn', 'Quảng NgãiHuyện Ba Tơ',
       'Quảng NgãiHuyện Nghĩa Hành', 'Quảng NgãiHuyện Sơn Tịnh',
       'Quảng NgãiThị xã Đức Phổ', 'Quảng NgãiHuyện Tư Nghĩa',
       'Quảng NgãiHuyện Sơn Tây', 'Quảng NgãiHuyện Minh Long',
       'Quảng NgãiHuyện Đức Phổ', 'Quảng NgãiHuyện Tây Trà']

filter_3_d_central2 = ['Quảng NgãiHuyện Sơn Hà', 'Quảng NgãiHuyện Trà Bồng']

filter_3_d_north1 = ['Điện Biên']

filter_3_d_north2 = ['Điện BiênHuyện Điện Biên', 'Điện BiênThành phố Điện Biên Phủ',
       'Điện BiênThị Xã Mường Lay', 'Điện BiênHuyện Mường Ảng']

filter_3_d_north3 = ['Điện BiênHuyện Tuần Giáo', 'Điện BiênHuyện Mường Chà',
       'Điện BiênHuyện Mường Nhé', 'Điện BiênHuyện Tủa Chùa',
       'Điện BiênHuyện Điện Biên Đông', 'Điện BiênHuyện Nậm Pồ']

filter_3_d_south1 = ['Kiên GiangThành phố Rạch Giá', 'Kiên GiangHuyện Giồng Riềng',
       'Kiên GiangHuyện U Minh Thượng', 'Kiên GiangHuyện Hòn Đất',
       'Kiên GiangHuyện Kiên Lương', 'Kiên GiangHuyện An Biên',
       'Kiên GiangHuyện Tân Hiệp', 'Kiên GiangHuyện An Minh',
       'Kiên Giang', 'Kiên GiangHuyện Châu Thành']

filter_3_d_south2 = ['Kiên GiangThành phố Hà Tiên', 'Kiên GiangThị xã Hà Tiên',
       'Kiên GiangHuyện Gò Quao', 'Kiên GiangHuyện Giang Thành',
       'Kiên GiangHuyện Vĩnh Thuận']

filter_3_d_south4 = ['Kiên Giang', 'Kiên GiangHuyện Kiên Hải',
       'Kiên GiangThành phố Phú Quốc', 'Kiên GiangHuyện Phú Quốc',
       'Quảng NgãiHuyện Lý Sơn']
